# How to use :
# docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '2'
services:
  am:
    hostname: ACCOUNT_MGR
    container_name: ACCOUNT_MGR
    build:
      context: ./env
      dockerfile: ./Dockerfile
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./env/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./env/mysql/data/:/var/lib/mysql/
      - ./env/mysql/sql/:/var/sql/
      - ./env/maven/repo/:/root/.m2/repository
      - ./ruoyi/:/opt/ruoyi/
      - ./bin/:/run/ruoyi/
    ports:
      - 8088:80
      - 3306:3306
    networks: 
      vpn:
        ipv4_address: 172.168.60.2
    restart: unless-stopped


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.60.0/24
          gateway: 172.168.60.1
    
    