USE account_mgr;

CREATE TABLE IF NOT EXISTS t_account (
    i_id           bigint(20)       not null auto_increment    comment '账号ID',
    i_user_id      bigint(20)       not null                   comment '外键ID-关联sys_user表',
    s_appname      varchar(64)      default ''                 comment '应用名称',
    s_site_1       varchar(512)     default ''                 comment '应用站点1',
    s_site_2       varchar(512)     default ''                 comment '应用站点2',
    s_site_3       varchar(512)     default ''                 comment '应用站点3',
    s_username     varchar(512)     default ''                 comment '登录账号',
    s_password     varchar(512)     default ''                 comment '登录密码',
    s_query_pwd    varchar(512)     default ''                 comment '查询密码',
    s_atm_pwd      varchar(512)     default ''                 comment '取款密码',
    s_pay_pwd      varchar(512)     default ''                 comment '支付密码',
    s_graphic_pwd  varchar(512)     default ''                 comment '图形密码',
    s_finger_pwd   varchar(512)     default ''                 comment '指纹密码',
    s_email        varchar(64)      default ''                 comment '绑定邮箱',
    s_phone        varchar(32)      default ''                 comment '绑定手机',
    s_idcard_num   varchar(64)      default ''                 comment '绑定身份证号',
    s_idcard_name  varchar(32)      default ''                 comment '绑定身份证名',
    s_question_1   varchar(512)     default ''                 comment '密码提示问题1',
    s_answer_1     varchar(512)     default ''                 comment '密码提示答案1',
    s_question_2   varchar(512)     default ''                 comment '密码提示问题2',
    s_answer_2     varchar(512)     default ''                 comment '密码提示答案2',
    s_question_3   varchar(512)     default ''                 comment '密码提示问题3',
    s_answer_3     varchar(512)     default ''                 comment '密码提示答案3',
    s_remark       varchar(512)     default ''                 comment '备注',
    d_update_time  datetime                                    comment '最后修改时间',
    primary key (i_id)
) engine=innodb auto_increment=1 comment = '应用账密表';
